[server]
headless = true
port = 8501
enableStaticServing = false
enableXsrfProtection = true
enableCORS = false

[theme]
base = "dark"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
hideSidebarNav = true
